# Generated by Django 4.1.5 on 2023-01-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=20)),
                ('photo_location', models.CharField(max_length=50)),
                ('photo_time', models.TimeField()),
                ('photo_text', models.CharField(max_length=100)),
            ],
        ),
    ]
